#
# configuration example
#

# identity provider config
idp:
  ssoTimeout: "1h"    # session expiration
  authTimeout: "10m"  # if the user doesn't proceed in this time will have to start again

# oauth provider config
oauth:
  issuer: https://kryptonite.example.com
  tokenExpiration: "15m"
  tokenSignatureHMAC: ${random.value}

clients:
  demo:
    clientId: demo
    clientSecret: demo
    type: CONFIDENTIAL
    redirectUris: [ "http://localhost/callback", "http://localhost:8080/callback" ]
    allowedScopes: [ "profile", "email", "phone" ]

# dummy data
users:
  - username: teo
    password: secret
    name: Teo Test
  - username: max
    password: secret
    name: Max Mustermann
  - username: erika
    password: secret
    name: Erika Mustermann
